import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";

import Footer from "../components/footer";
import Header from "../components/header";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <div className="h-screen flex flex-col">
          <Header />
          {/* <div className="flex flex-col items-center">
          <div className="container">{children}</div>
        </div> */}
          <div className="flex-grow">{children}</div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
